version: '2'
services:
  app:
    container_name: app.tokenizer.local
    build: ../../app
    image: tokenizer
    env_file:
      - ./config.env
    ports:
      - 80:80
    volumes:
      - ../../app:/go/src/app
    links:
      - postgres:postgres.tokenizer.local
    restart: always

  postgres:
    image: postgres
    container_name: postgres.tokenizer.local
    env_file:
      - ./config.env
    ports:
      - 5432:5432
    volumes:
      - ../../postgres/data:/var/lib/postgresql/data/pgdata

